// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAgFAg-iZY6dH-0uQJTz0nQaWRhK3rZ8',
    appId: '1:778337606410:web:1001f84a9f095f4d9b78f3',
    messagingSenderId: '778337606410',
    projectId: 'lost-and-found-ff4ea',
    authDomain: 'lost-and-found-ff4ea.firebaseapp.com',
    storageBucket: 'lost-and-found-ff4ea.firebasestorage.app',
    measurementId: 'G-KQK17VNSJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1k_O1nuFxvGPVHx211id3ar4anaKaB4',
    appId: '1:778337606410:android:8aac23a97736e1da9b78f3',
    messagingSenderId: '778337606410',
    projectId: 'lost-and-found-ff4ea',
    storageBucket: 'lost-and-found-ff4ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8M9xKRUobp1snCwwTgtfVJCoFZZFXrQ',
    appId: '1:778337606410:ios:38b451b770f7d57d9b78f3',
    messagingSenderId: '778337606410',
    projectId: 'lost-and-found-ff4ea',
    storageBucket: 'lost-and-found-ff4ea.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );
}
