import '../../shared/models/item_model.dart';

class MockData {
  // Shared in-memory items list
  static final List<Item> items = [
    const Item(
      id: '1',
      title: 'Gold Rolex Watch',
      isLost: true,
      timeAgo: '2h ago',
      location: 'Central Park, NY',
      description: 'Found a gold rolex watch near the fountain.',
      imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&q=80&w=200',
      category: 'Electronics',
      status: 'LOST',
    ),
    const Item(
      id: '2',
      title: 'Friendly Golden Retriever',
      isLost: false,
      timeAgo: '5h ago',
      location: 'Brooklyn, NY',
      description: 'Found a friendly golden retriever near the park.',
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
      category: 'Pets',
      status: 'FOUND',
    ),
    const Item(
      id: '3',
      title: 'Brown Leather Wallet',
      isLost: true,
      timeAgo: '1d ago',
      location: 'Grand Central Terminal',
      description: 'Lost a brown leather wallet near the station.',
      imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=200',
      category: 'Wallets',
      status: 'LOST',
    ),
    const Item(
      id: '4',
      title: 'iPhone 13 Pro - Blue',
      isLost: true,
      timeAgo: '3h ago',
      location: 'Times Square, NY',
      description: 'Lost my blue iPhone 13 Pro in Times Square.',
      imageUrl: 'https://images.unsplash.com/photo-1633114128174-2f8aa49759b0?auto=format&fit=crop&q=80&w=200',
      category: 'Electronics',
      status: 'LOST',
    ),
    const Item(
      id: '5',
      title: 'Keys with Red Keychain',
      isLost: false,
      timeAgo: '1h ago',
      location: 'Chelsea Market',
      description: 'Found a set of keys with a red keychain.',
      imageUrl: 'https://images.unsplash.com/photo-1619183495208-0f04e137286a?auto=format&fit=crop&q=80&w=200',
      category: 'Keys',
      status: 'FOUND',
    ),
    const Item(
      id: '6',
      title: 'Blue Passport Cover',
      isLost: false,
      timeAgo: '4h ago',
      location: 'JFK Airport Terminal 4',
      description: 'Found a blue passport cover near the gate.',
      imageUrl: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&q=80&w=200',
      category: 'Documents',
      status: 'FOUND',
    ),
    const Item(
      id: 'rec_1',
      title: 'Sony WH-1000XM4 Headphones',
      timeAgo: '2m ago',
      location: 'Central Park Mall, Food Court',
      description: 'Found Sony headphones in the food court area. Black color, slightly scratched.',
      isLost: false,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400',
      category: 'Electronics',
      status: 'FOUND',
    ),
    const Item(
      id: 'rec_2',
      title: 'Golden Retriever Puppy',
      timeAgo: '15m ago',
      location: 'Oakwood Residences Park',
      description: 'Answers to "Cooper". Very friendly, found near the children\'s playground.',
      isLost: false,
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
      category: 'Pets',
      status: 'FOUND',
    ),
    const Item(
      id: 'rec_3',
      title: 'Brown Leather Wallet',
      timeAgo: '1h ago',
      location: 'Grand Central Terminal Station',
      description: 'Lost a brown leather wallet. Contains transit cards and some cash.',
      isLost: true,
      imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=400',
      category: 'Wallets',
      status: 'LOST',
    ),
    const Item(
      id: 'admin_1',
      title: 'Leather Wallet',
      location: 'PETS AREA',
      description: 'A premium brown leather bi-fold wallet containing multiple store cards, cash receipts, and a small metal token. Found under the benches.',
      isLost: false,
      imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=200',
      timeAgo: '2/12/2026',
      category: 'ACCESSORIES',
      status: 'FOUND',
    ),
    const Item(
      id: 'admin_2',
      title: 'Blue Backpack',
      location: 'BAGS',
      description: 'A standard blue canvas school backpack with yellow zip accents. Contains an empty thermos flask and several notebooks.',
      isLost: true,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=200',
      timeAgo: '2/10/2026',
      category: 'TRAVEL',
      status: 'LOST',
    ),
    const Item(
      id: 'admin_3',
      title: 'Nike Sports Shoe',
      location: 'FOOTWEAR',
      description: 'A single red Nike zoom trainer shoe, size US 9. Left behind near the lockers inside gym court B.',
      isLost: true,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=200',
      timeAgo: '2/08/2026',
      category: 'APPAREL',
      status: 'LOST',
    ),
  ];

  // In-memory mock user accounts
  static final List<Map<String, dynamic>> users = [
    {
      'uid': 'admin_user_1',
      'email': 'admin@admin.com',
      'name': 'Super Admin',
      'role': 'admin',
      'isBanned': false,
    },
    {
      'uid': 'test_user_1',
      'email': 'tayyab@gmail.com',
      'name': 'Tayyab Ali',
      'role': 'user',
      'isBanned': false,
    },
    {
      'uid': 'test_user_2',
      'email': 'sarah@gmail.com',
      'name': 'Sarah Connor',
      'role': 'user',
      'isBanned': false,
    },
    {
      'uid': 'test_user_3',
      'email': 'marcus@gmail.com',
      'name': 'Marcus Chen',
      'role': 'user',
      'isBanned': false,
    },
  ];

  // In-memory notifications mock
  static final List<Map<String, dynamic>> notifications = [
    {
      'id': 'notif_1',
      'title': 'New Match Found!',
      'description': 'Your lost wallet matches a found wallet nearby.',
      'type': 'alert',
      'timeAgo': '10m ago',
    },
    {
      'id': 'notif_2',
      'title': 'Message from Marcus Chen',
      'description': 'Hey, I think I have your keys. Let me know when...',
      'type': 'chat',
      'timeAgo': '2h ago',
    },
  ];
}
